USE gestion_bibliothèque;
CREATE TABLE DOCUMENT (
        IDDOC INTEGER ,
        TITRE VARCHAR (50),
        ANNEEPUB INT,
        EDITEUR VARCHAR (50) ,
        PRIMARY KEY(IDDOC)
);
CREATE TABLE LIVRE (
		ISBN INTEGER ,
        IDDOC INTEGER ,
		AUTEUR VARCHAR (50),
        primary key(ISBN) ,
        FOREIGN KEY (IDDOC) REFERENCES DOCUMENT(IDDOC)
      
);
CREATE TABLE PERIODIQUE (
		ISSN INTEGER,
        IDDOC INTEGER ,
		VOLUME VARCHAR (50) ,
        primary key(ISSN) ,
        FOREIGN KEY (IDDOC) REFERENCES DOCUMENT(IDDOC)
);
CREATE TABLE EXEMPLAIRE (
        ID_EXM INT ,
        IDDOC INTEGER ,
        NUMERO_ORD INTEGER ,
        DATE_ACHAT DATE,
        STATUT VARCHAR (50),
        ETAT VARCHAR (50) ,
        PRIMARY KEY(ID_EXM) ,
        FOREIGN KEY (IDDOC) REFERENCES DOCUMENT(IDDOC)
);
CREATE TABLE UTILISATEUR (
        ID_UTIL INTEGER ,
        NOM_U VARCHAR (50),
        PRENOM_U VARCHAR (50),
        CATEGORIE VARCHAR (50) ,
        PRIMARY KEY(ID_UTIL) 
);
CREATE TABLE BIBLIOTHECAIRE (
		ID_BIB INTEGER ,
        NOM_B VARCHAR (50),
        PRENOM_B VARCHAR (50),
        POSITION VARCHAR (50) ,
        PRIMARY KEY(ID_BIB)
);
CREATE TABLE EMPRUNT (
        ID_EMP INT,
        ID_UTIL INTEGER ,
        ID_EXM INTEGER ,
        ID_BIB INTEGER ,
        DATE_DEBUT DATE,
        DATE_FIN DATE,
        DATE_RELANCE DATE,
        NUM_RELANCE INTEGER CHECK (NUM_RELANCE>=0),
		PRIMARY KEY(ID_EMP) ,
		FOREIGN KEY (ID_UTIL) REFERENCES UTILISATEUR(ID_UTIL),
        FOREIGN KEY (ID_EXM) REFERENCES EXEMPLAIRE(ID_EXM),
        FOREIGN KEY (ID_BIB) REFERENCES BIBLIOTHECAIRE(ID_BIB)
);







